# Generated by Django 3.1.1 on 2021-02-24 08:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('photo_paths', jsonfield.fields.JSONField(default=[])),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('subcats', jsonfield.fields.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('item_id', models.IntegerField()),
            ],
        ),
    ]
