# Generated by Django 3.1.1 on 2021-02-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
