# Generated by Django 3.1.1 on 2020-12-06 11:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201029_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='subcats',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
