# Generated by Django 3.1.1 on 2020-12-06 20:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201206_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='item',
            name='photo_paths',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
