# Generated by Django 3.1.1 on 2020-12-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201212_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
