# Generated by Django 3.1.1 on 2020-12-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201213_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('item_id', models.IntegerField()),
            ],
        ),
    ]
